module.exports = [
    {
        name: 'Gavin Nicol',
        displayName: 'Gavin<br>Nicol',
        description: 'Gavin has been a technology leader and innovator for 25+ years working at research centres, startups and corporations in Japan, US and Netherlands. A founding member of the World Wide Web Consortium (W3C), he played a significant role in the development and prototype implementation of the HTML, HTTP, XML, XSL, DOM, XPath, SVG, XQuery and XLink standards. He has influenced many of the technologies underlying the modern web and is considered "the father of I18N on the WWW".',
        linkedin: 'https://www.linkedin.com/in/gtnicol/',
        avatar: '/img/team/gavin.jpg',
        role: 'CTO, Context Labs BV',
    },
    {
        name: 'Anthony Eufemio',
        displayName: 'Anthony<br>Eufemio',
        description: 'Anthony is a 19 year veteran of the software development, computer security, and IT industries. He is the Chief Technology Officer and Co-Founder of Digix Global, the world’s first smart asset company and performed the first ever fully on-chain Ethereum crowdsale. As an early adopter and contributor in the Ethereum ecosystem, he sent the first ever live Ethereum transaction, deployed the first ‘dummy’ contract and developed several open source Ethereum tools and libraries.',
        linkedin: 'https://www.linkedin.com/in/anthony-eufemio-a4284b100/',
        avatar: '/img/team/Anthony.jpg',
        role: 'CTO, Digixdao',
    },
    {
        name: 'Michael Widjaja',
        displayName: 'Michael<br>Widjaja',
        description: 'Michael is a retired Accenture Partner and acted as Chief Executive of the Technology Architecture Consulting Practice for Latin America as well as Global Head of Application Security Technology Practice, working with global clients throughout Latin America, Europe, United States and Asia. He was responsible for delivering, managing and selling IT programs of complex software solutions.',
        linkedin: 'https://www.linkedin.com/in/michaelwidjaja/',
        avatar: '/img/team/michael.jpg',
        role: 'Managing Director, Accenture',
    },
    {
        name: 'Reinout te Brake',
        displayName: 'Reinout<br/>te Brake',
        description: 'Reinout is well known in the international gaming business - publishers, developers, entrepreneurs and CEOs of large corporations seek his advice on technical, operational, strategic and commercial matters. His company GWC Investments is a consultancy and (seed) investment firm offering online gaming expertise within the gaming industry. It consists of a team of highly experienced gaming professionals and industry veterans in the field of Esports, iGaming and (mobile) gaming.',
        linkedin: 'https://www.linkedin.com/in/reinouttebrake/',
        avatar: '/img/team/reinout.png',
        role: 'Gaming Industry Expert',
    },
    {
        name: 'Richard van Barneveld',
        displayName: 'Richard van<br/>Barneveld',
        description: 'Richard’s areas of expertise include strategic business planning, corporate business development and fundraising for tech startups. He is the Strategic Director and Founder of Utomik Inc., a game subscription service with partners from Disney, Take2, Ubisoft, Warner and more. Prior to that he was Strategic Director at Kalydo, which powers games for game publishers & developers from companies that include The Cartoon Network (Turner), Gungho, Gameforge, COG, Chiyu, Gamigo and Gravity.',
        linkedin: 'https://www.linkedin.com/in/richardvanbarneveld',
        avatar: '/img/team/richard.png',
        role: 'Strategic Director, Utomik Inc.',
    },
    {
        name: 'Gareth Lewis',
        displayName: 'Gareth<br>Lewis',
        description: 'Gareth is the Head of Technology for Poland and Eastern Europe at a top-tier investment bank. He is an experienced leader in FinTech with expertise in blockchain research and emerging financial technologies. In May 2018, Gareth was awarded a grant from the Ethereum Foundation to develop his project on the Ethereum blockchain (a cryptowallet incorporating smart contract custody).',
        linkedin: 'https://www.linkedin.com/in/garethtlewis/',
        avatar: '/img/team/GarethLewis.png',
        role: 'Solidity Expert',
    },
];
