module.exports = [
    {
        name: 'Peter van Grinsven',
        displayName: 'Peter van<br/>Grinsven',
        description: 'Peter is a serial entrepreneur. After receiving his Masters Degree from Maastricht University, he started at PWC as an internet business consultant. Operating between strategy and technology has been his passion ever since. His company, CONNAXIS, which has offices in 6 locations, creates magical new experiences via innovative technologies. In 2009, he launched Guerra Creativa, a successful creative crowdsourcing marketplace. CONNAXIS has focused on blockchain technologies since 2015.',
        linkedin: 'https://www.linkedin.com/in/connaxisstaycompetitive/',
        avatar: '/img/team/peter.jpg',
        role: 'CEO',
    },
    {
        name: 'Pawel Pinio',
        displayName: 'Paweł<br>Pinio',
        description: 'Paweł is a senior software engineer with extensive experience in building fault tolerant back-end systems. He started his career as a full stack developer before moving to work on diagnostics and radiology information systems. He then moved into interdisciplinary consulting which allowed him to build transformative platforms. Paweł is a strong evangelist of distributed systems, blockchain and decentralization and a firm technical enthusiast of the Ethereum platform and community.',
        linkedin: 'https://www.linkedin.com/in/pawelpinio/',
        avatar: '/img/team/pawel.jpg',
        role: 'CTO',
    },
    {
        name: 'Freddy Bucknell',
        displayName: 'Freddy<br/>Bucknell',
        description: 'Freddy is an ICAEW Chartered Accountant having worked for Deloitte LLP in the Financial Services Advisory team in London where managed a range of clients in insurance, banking and asset finance. He worked in the Deloitte London office as a Manager specializing in banking, where his main client was a FTSE 250 bank. Freddy took an early interest in blockchain technology and has been an active trader and avid investor in cryptocurrencies.',
        linkedin: 'https://www.linkedin.com/in/freddy-bucknell-0985a322/',
        avatar: '/img/team/freddy.png',
        role: 'COO',
    },
    {
        name: 'Gonzalo Balabasquer',
        displayName: 'Gonzalo<br>Balabasquer',
        description: 'Gonzalo is a systems engineer who started his professional career as a PHP programmer. In the years that followed, he led a team of developers at a fast-paced agency located in Argentina. Recently, he followed his passion and returned to a technical position to leverage his IT experience as a full stack blockchain developer participating as an active developer of the MakerDao project.',
        linkedin: 'https://www.linkedin.com/in/gbalabasquer/',
        avatar: '/img/team/gonzalo.jpg',
        role: 'Blockchain Engineer',
    },
    {
        name: 'Bastien Hugon',
        displayName: 'Bastien<br>Hugon',
        description: 'Bastien is a project manager with excellent strategic and operational skills. He has leadership competencies for team building, client relations, negotiation, decision making, problem solving and conflict management in French, Spanish and English. He has 10+ years of experience in QA, IT infrastructure and service delivery working with companies like HCL, DANA, Ford, L’Oreal, Nokia and bioMerieux.',
        linkedin: 'https://www.linkedin.com/in/bastienhugon/',
        avatar: '/img/team/bastien.jpg',
        role: 'Project Manager',
    },
    {
        name: 'Marcin Gierlak',
        displayName: 'Marcin<br>Gierlak',
        description: 'Marcin has a strong background in software engineering including cloud, mobile platforms, cryptography and security, system level programming, and systems development life cycle. He has experience in developing and implementing concepts and technologies for IoT, hands-on experience with Ethereum/Solidity, blockchain technologies, distributed ledger, cryptocurrencies and Smart Contracts.',
        linkedin: 'https://www.linkedin.com/in/marcingierlak/',
        avatar: '/img/team/marcin.jpg',
        role: 'Blockchain Solutions Architect',
    },
    {
        name: 'Marlena Pawlukowska',
        displayName: 'Marlena<br>Pawlukowska',
        description: 'Marlena gained extensive experience in web development and digital marketing at several leading digital agencies and through her freelance work. She has an eye for good design, meticulous attention to quality and detail and is addicted to following the newest trends and searching for smart solutions. Her work is driven by a conviction that only from a well-balanced mixture of tech, design and creativity can you craft digital experiences that people fall in love with.',
        linkedin: 'https://www.linkedin.com/in/marlenape/',
        avatar: '/img/team/marlena.png',
        role: 'Web Developer',
    },
    {
        name: 'Guido Hakkenberg',
        displayName: 'Guido<br/>Hakkenberg',
        description: 'Guido Hakkenberg is a multicultural former business & innovation student who\'s passion for innovation has lead him to the world of blockchain and cryptocurrencies. He has previous experience in social media management for a large IT company. Guido is likeable and easy-going and always manages to make friends wherever he goes. He speaks fluent English, French, Dutch and dabbles in Japanese.',
        linkedin: 'https://www.linkedin.com/in/guido-hakkenberg/',
        avatar: '/img/team/guido.png',
        role: 'Community Manager',
    },
    {
        name: 'Anna Walo-Nowakowska',
        displayName: 'Anna Walo<br/>Nowakowska',
        description: 'Anna is a graphic designer with a comprehensive skillset who values high quality design and attention to detail. She graduated from the Academy of Fine Arts in 2012 and has over 10 years of experience in brand design, packaging and web design. She accepts no half-measures and demands high standards from herself and those around her. Anna tends to geek out over brand design and typography.',
        linkedin: 'https://www.linkedin.com/in/anna-walo-nowakowska-501b6769/',
        avatar: '/img/team/anna.png',
        role: 'Graphic Designer',
    },
    {
        name: 'Szymon Bury',
        displayName: 'Szymon Bury',
        description: 'Szymon is a front-end developer, with significant experience in hybrid mobile development and well-grounded aspirations for full stack development. Recently he stepped into the world of digital ledgers, mastering techniques around React/Ionic/web3.js driven development of decentralised applications.',
        linkedin: 'https://www.linkedin.com/in/szymon-bury-36b7a698/',
        avatar: '/img/team/szymon.jpg',
        role: 'Mobile/Web Developer',
    },
];
