module.exports = [
    {
        name: 'Peter van Grinsven',
        displayName: 'Peter van<br/>Grinsven',
        description: 'Peter is a serial entrepreneur. After receiving his Masters Degree from Maastricht University, he started at PWC as an internet business consultant. He has launched several successful platforms including Expatica and Guerra Creativa. His company, Connaxis, which has offices in 6 locations, creates magical new experiences via innovative technologies. Connaxis has focused on blockchain technologies since 2015.',
        linkedin: 'https://www.linkedin.com/in/connaxisstaycompetitive/',
        avatar: '/img/team/peter.jpg',
        role: 'CEO',
    },
    {
        name: 'Freddy Bucknell',
        displayName: 'Freddy<br/>Bucknell',
        description: 'Freddy is a Chartered Accountant of the Institute of Chartered Accountants of England and Wales. The majority of his career so far has been at Deloitte LLP. He joined as a graduate in the UK Financial Services Audit and Advisory team and led engagements for a range of clients in banking, insurance and asset finance. He then worked as a Manager in the Banking & Capital Markets Division in London, leading engagements for FTSE 250 clients.',
        linkedin: 'https://www.linkedin.com/in/freddy-bucknell-0985a322/',
        avatar: '/img/team/freddy.png',
        role: 'COO',
    },
    {
        name: 'Marcin Gierlak',
        displayName: 'Marcin<br>Gierlak',
        description: 'Marcin has a strong background in software engineering, formerly working at IBM and HID Global, including cloud, mobile platforms, cryptography and security, system level programming, and systems development life cycle. He has experience in developing and implementing concepts and technologies for IoT, hands-on experience with Ethereum/Solidity, blockchain technologies, distributed ledger, cryptocurrencies and Smart Contracts.',
        linkedin: 'https://www.linkedin.com/in/marcingierlak/',
        avatar: '/img/team/marcin.jpg',
        role: 'CTO',
    },
    {
        name: 'Szymon Bury',
        displayName: 'Szymon<br/>Bury',
        description: 'Szymon is a front-end developer, with significant experience in hybrid mobile development and well-grounded aspirations for full stack development. He is a former mobile and web developer at Phenomaly and IT specialist at Unima 2000. Recently he stepped into the world of digital ledgers, mastering techniques around React, Ionic and web3.js driven development of decentralised applications.',
        linkedin: 'https://www.linkedin.com/in/szymon-bury-36b7a698/',
        avatar: '/img/team/szymon.jpg',
        role: 'Mobile/Web Developer',
    },
    {
        name: 'Victor Kashirin',
        displayName: 'Victor<br>Kashirin',
        description: 'Victor’s range of professional interests includes front-end development, UX and UI design, data analytics and visualisation. He has experience in doing academic research, developing enterprise applications for large corporations as well as helping to shape environmental agendas through research, data preparation and presentation. On the front-end side, he is most curious about making blockchain-enabled applications accessible, intuitive and reliable.',
        linkedin: 'https://www.linkedin.com/in/victorkashirin/',
        avatar: '/img/team/VictorK.png',
        role: 'User Experience / Frontend',
    },
    {
        name: 'Bas van Oostveen',
        displayName: 'Bas van<br>Oostveen',
        description: 'Bas is a blockchain expert that mined his first Bitcoin in 2010 and has been involved in blockchain ever since. With over 20 years of IT experience and a background in security and open source software he has created engineering departments, lead architecture design, development & management of several high volume internet and security platforms. Under which are real-time trading and advertisement systems and digital media platforms with over 9,000 websites, sustaining traffic of over 4gbit/s, combining micropayments, credit-card handling and fraud detection/prevention.',
        linkedin: 'https://www.linkedin.com/in/oostveen/',
        avatar: '/img/team/BasvO2.png',
        role: 'Blockchain Lead',
    },
    {
        name: 'Vincent Bonhomme',
        displayName: 'Vincent<br>Bonhomme',
        description: 'Vince has over 11 years experience in the game industry, starting out in quality assurance, with four years as a localisation manager and three years as a General Manager. He resides in Tokyo, Japan, and now manages the Asia region for ExeQuo and Lionbridge Game Services. He has worked on 100+ titles including dozens of AAA games. He is also the co-founder of Tabletop Pixel, an indie studio based in Tokyo that creates HTML5 and Unity games.',
        linkedin: 'https://www.linkedin.com/in/bonhommevincent/',
        avatar: '/img/team/vincent.jpg',
        role: 'Business Development',
    },
    {
        name: 'Marlena Pawlukowska',
        displayName: 'Marlena<br>Pawlukowska',
        description: 'Marlena gained extensive experience in web development and digital marketing at several leading digital agencies. She has an eye for good design and a meticulous attention to quality and detail and is addicted to following the newest trends and searching for smart solutions. Her work is driven by a conviction that only from a well-balanced mixture of tech, design and creativity can you craft digital experiences that people fall in love with.',
        linkedin: 'https://www.linkedin.com/in/marlenape/',
        avatar: '/img/team/marlena.png',
        role: 'Web Developer',
    },
    {
        name: 'Guido Hakkenberg',
        displayName: 'Guido<br/>Hakkenberg',
        description: 'Guido is a multicultural former Business & Innovation graduate whose passion for technology innovation has led him to the world of blockchain and cryptocurrencies. He has experience in social media and community management having previously worked on several clients of the specialised social media solutions agency Curlad. He speaks fluent English, French and Dutch, and has a conversational level of Japanese.',
        linkedin: 'https://www.linkedin.com/in/guido-hakkenberg/',
        avatar: '/img/team/guido.png',
        role: 'Community Manager',
    },
    {
        name: 'Anna<br>Walo-Nowakowska',
        displayName: 'Anna Walo<br/>Nowakowska',
        description: 'Anna is a graphic designer with a comprehensive skill set who values high quality design and attention to detail. She graduated from the Academy of Fine Arts in 2012 and has over 10 years of experience in brand design, packaging and web design. She accepts no half-measures and demands high standards from herself and those around her. Anna tends to geek out over brand design and typography.',
        linkedin: 'https://www.linkedin.com/in/anna-walo-nowakowska-501b6769/',
        avatar: '/img/team/anna.png',
        role: 'Senior Graphic Designer',
    },
    {
        name: 'Enver Altuntas',
        displayName: 'Enver<br>Altuntas',
        description: 'Enver has significant experience in digital marketing, working as a private marketing consultant and leading several marketing teams. He has worked for a number of companies, from startups to large multinationals, to digitize their marketing operations and grow online. He is an avid gamer for over 15 years and in the crypto-world for some time now. He is combining his passion for marketing, gaming and crypto all at once at nTitle.',
        linkedin: 'https://www.linkedin.com/in/enveraltuntas/',
        avatar: '/img/team/enver.png',
        role: 'Marketing Manager',
    },
    {
        name: 'Edward Hewett',
        displayName: 'Edward<br>Hewett',
        description: 'Edward brings a wealth of experience after 10 years in motorsport, having won 3 F1 World Championships and worked in Marketing, Brand Representation and Product Development for the likes of Alpinestars and RedBull Racing. He is a long term and active member of the crypto community, as both an investor and ICO researcher. He has a great passion and strong belief in the positive effects that Blockchain technology can bring.',
        linkedin: 'https://www.linkedin.com/in/edward-hewett/',
        avatar: '/img/team/edward.png',
        role: 'Marketing & Communications',
    }
];
