module.exports = {
    sections: [
        {
            tab: 'Frustrated with high fees?',
            themeIcon: '1_exorbitant_fees.svg',
            theme: 'dev',
            headline: 'Frustrated with exorbitant listing fees charged by today’s gaming marketplaces?',
            subHeadline: 'nTitle gives you back your control!',
            text: '<p>Our powerful, decentralized gaming peer-to-peer marketplace will remove the “middleman” and will completely redefine the industry. That means you can now offer games directly to customers without “middlemen” taking a 30% cut.</p>',
        },
        {
            tab: 'Disappointed with your ROI?',
            theme: 'dev',
            themeIcon: '5_dissapointed.svg',
            headline: 'Disappointed with the ROI you are getting on your game development?',
            subHeadline: 'nTitle gives you back your options!',
            text: '<p>If you choose to allow your games to be resold on our peer-to-peer marketplace, you set the terms and receive a commission on each resale which means that you continue to make money long after the original purchase.</p>',
        },
        {
            tab: 'Unhappy with marketing support?',
            theme: 'dev',
            themeIcon: '3_marketing support.svg',
            headline: 'Unhappy with the marketing support you receive from current gaming marketplaces?',
            subHeadline: 'nTitle gives you back your power!',
            text: '<p>By combining gamification and brand ambassador marketing with a robust and unique type of  affiliate program, we’re empowering an entire gaming community and turning them into a marketing powerhouse that you can tap into.</p>',
        },
        {
            tab: 'Concerned about funding?',
            theme: 'dev',
            themeIcon: '6_business_side.svg',
            headline: 'Love developing games but concerned about the business side of gaming?',
            subHeadline: 'nTitle gives you back your opportunities!',
            text: '<p>The nTitle marketplace enables you to fund new projects through our crowdfunding channel, pre-sell new games and game items, pre-test new projects with a select group of gamers, get traction before launching and receive feedback on ideas before committing all in.</p>',
        },
        {
            tab: 'Annoyed with the cost of games?',
            theme: 'gamer',
            themeIcon: '4_high_costs.svg',
            headline: 'Annoyed with the high cost of being a gamer in today’s market?',
            subHeadline: 'nTitle gives you back your rights',
            text: '<p>We’re opening up a peer-to-peer market where you’ll actually own the game that you rightfully purchased. You’ve paid to play it and now you’re also nTitled to re-sell, trade, gift or even rent it on nTitle’s revolutionary, new gaming marketplace. </p>',
        },
        {
            tab: 'Wish you had more of a say?',
            theme: 'gamer',
            themeIcon: '2_sale_lend.svg',
            headline: 'Wish you had more opportunities to help out your favourite developers to benefit both of you?',
            subHeadline: 'nTitle gives you back your possibilities!',
            text: '<p>We\'re introducing a dedicated crowdfunding channel to our marketplace. You can sponsor your favourite games, provide pre-launch feedback and be one of the first to play it when it\'s released. Help promote it through social media and earn money to further reduce your cost of gaming. </p>',
        },
    ],
};
